services:

  nginx:
    image: nginx:latest
    container_name: cloud-eln-nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - web

  web:
    build: .
    container_name: cloud-eln-app

    expose:
      - "5000"

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/cloud_eln

  db:
    image: postgres:16

    container_name: cloud-eln-db

    restart: always

    environment:
      POSTGRES_DB: cloud_eln
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: